version: "3.2"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
    ports: 
      - "5432:5432"
  api:
    depends_on:
        - db  
    build: ./api  
    volumes:
        - ./api:/api
    ports:
        - "8000:8000"
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  client:
    build: ./client 
    ports: 
      - "8080:8080"
    command: /bin/sh -c "yarn dev"
    depends_on:
        - api