# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: API Pipeline

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      db: 
        image: postgres
        env:
          POSTGRES_DB: myproject
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      working-directory: api
      run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
    - name: Tests
      working-directory: api
      run: |
          python manage.py migrate
          python manage.py test      
    
    - name: Generate coverage report
      working-directory: api
      run: |
          coverage run --source='.' manage.py test
          coverage xml
    
    - name: Upload to coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        working-directory: api
        fail_ci_if_error: true

    - name: Lint
      working-directory: api
      run: python3.9 -m flake8
          
